s/ NP / t1 /g
s/ SPECNP / t2 /g
s/ NBAR / t3 /g
s/ S\[+R\] / t4 /g
s/ S\/NP / t5 /g
s/ VP\/NP / t6 /g
s/ Z0 / t7 /g
s/ VP / t8 /g
s/ Z1 / t9  /g
s/ V\[SUBCAT2\] / t10 /g
s/ V\[SUBCAT3\] / t11 /g
s/ V\[SUBCAT4\] / t12 /g
s/ PP\[to\] / t13 /g
s/ PBAR\[to\] / t14 /g
s/ P\[to\] / t15 /g
s/ PP\[for\] / t16 /g
s/ PBAR\[for\] / t17 /g
s/ P\[for\] / t18 /g
s/ NP\[+R\] / t19 /g
s/ DT / t20 /g
s/ N / t21 /g
s/ ADJ / t22 /g
s/ NP\/NP / E /g
