bless <- subset(read.table("BagOfWords.data", header=TRUE), grepl('/N', Relatum, fixed=TRUE))
kruskalLabel <- function(r){
    return(sprintf("%s (%s p=%g)", r$data.name, r$method, r$p.value))
}
attach(bless)
print((wilcox.test(BagOfWords_KL[Relation=="Coord"], BagOfWords_KL[Relation=="Hyper"]))$p.value)
print((wilcox.test(BagOfWords_KL[Relation=="Coord"], BagOfWords_KL[Relation=="Mero"]))$p.value)
print((wilcox.test(BagOfWords_KL[Relation=="Coord"], BagOfWords_KL[Relation=="RandomN"]))$p.value)
print((wilcox.test(BagOfWords_KL[Relation=="Hyper"], BagOfWords_KL[Relation=="Mero"]))$p.value)
print((wilcox.test(BagOfWords_KL[Relation=="Hyper"], BagOfWords_KL[Relation=="RandomN"]))$p.value)
print((wilcox.test(BagOfWords_KL[Relation=="Mero"], BagOfWords_KL[Relation=="RandomN"]))$p.value)
print((wilcox.test(BagOfWords_LK[Relation=="Coord"], BagOfWords_LK[Relation=="Hyper"]))$p.value)
print((wilcox.test(BagOfWords_LK[Relation=="Coord"], BagOfWords_LK[Relation=="Mero"]))$p.value)
print((wilcox.test(BagOfWords_LK[Relation=="Coord"], BagOfWords_LK[Relation=="RandomN"]))$p.value)
print((wilcox.test(BagOfWords_LK[Relation=="Hyper"], BagOfWords_LK[Relation=="Mero"]))$p.value)
print((wilcox.test(BagOfWords_LK[Relation=="Hyper"], BagOfWords_LK[Relation=="RandomN"]))$p.value)
print((wilcox.test(BagOfWords_LK[Relation=="Mero"], BagOfWords_LK[Relation=="RandomN"]))$p.value)
pdf(file = "BagOfWords.pdf")
library(Hmisc)
Ecdf(BagOfWords_KL, group=Relation, xlab=kruskalLabel(kruskal.test(BagOfWords_KL     ~ Relation)), label.curves=list(keys=1:4), xlim=c(0,1), col=c("red","blue","purple","darkgreen"))
Ecdf(BagOfWords_LK, group=Relation, xlab=kruskalLabel(kruskal.test(BagOfWords_LK     ~ Relation)), label.curves=list(keys=1:4), xlim=c(0,1), col=c("red","blue","purple","darkgreen"))
dev.off()
detach(bless)
