bless <- read.table("NounPhrase.data", header=TRUE)
kruskalLabel <- function(r){
    return(sprintf("%s (%s p=%g)", r$data.name, r$method, r$p.value))
}
attach(bless)
print((wilcox.test(r_np_npb_KL_[Relation=="Coord"], r_np_npb_KL_[Relation=="Hyper"]))$p.value)
print((wilcox.test(r_np_npb_KL_[Relation=="Coord"], r_np_npb_KL_[Relation=="Mero"]))$p.value)
print((wilcox.test(r_np_npb_KL_[Relation=="Coord"], r_np_npb_KL_[Relation=="RandomN"]))$p.value)
print((wilcox.test(r_np_npb_KL_[Relation=="Hyper"], r_np_npb_KL_[Relation=="Mero"]))$p.value)
print((wilcox.test(r_np_npb_KL_[Relation=="Hyper"], r_np_npb_KL_[Relation=="RandomN"]))$p.value)
print((wilcox.test(r_np_npb_KL_[Relation=="Mero"], r_np_npb_KL_[Relation=="RandomN"]))$p.value)
print((wilcox.test(r_np_npb_LK_[Relation=="Coord"], r_np_npb_LK_[Relation=="Hyper"]))$p.value)
print((wilcox.test(r_np_npb_LK_[Relation=="Coord"], r_np_npb_LK_[Relation=="Mero"]))$p.value)
print((wilcox.test(r_np_npb_LK_[Relation=="Coord"], r_np_npb_LK_[Relation=="RandomN"]))$p.value)
print((wilcox.test(r_np_npb_LK_[Relation=="Hyper"], r_np_npb_LK_[Relation=="Mero"]))$p.value)
print((wilcox.test(r_np_npb_LK_[Relation=="Hyper"], r_np_npb_LK_[Relation=="RandomN"]))$p.value)
print((wilcox.test(r_np_npb_LK_[Relation=="Mero"], r_np_npb_LK_[Relation=="RandomN"]))$p.value)
print((wilcox.test(l_npb_KL[Relation=="Coord"], l_npb_KL[Relation=="Hyper"]))$p.value)
print((wilcox.test(l_npb_KL[Relation=="Coord"], l_npb_KL[Relation=="Mero"]))$p.value)
print((wilcox.test(l_npb_KL[Relation=="Coord"], l_npb_KL[Relation=="RandomN"]))$p.value)
print((wilcox.test(l_npb_KL[Relation=="Hyper"], l_npb_KL[Relation=="Mero"]))$p.value)
print((wilcox.test(l_npb_KL[Relation=="Hyper"], l_npb_KL[Relation=="RandomN"]))$p.value)
print((wilcox.test(l_npb_KL[Relation=="Mero"], l_npb_KL[Relation=="RandomN"]))$p.value)
print((wilcox.test(l_npb_LK[Relation=="Coord"], l_npb_LK[Relation=="Hyper"]))$p.value)
print((wilcox.test(l_npb_LK[Relation=="Coord"], l_npb_LK[Relation=="Mero"]))$p.value)
print((wilcox.test(l_npb_LK[Relation=="Coord"], l_npb_LK[Relation=="RandomN"]))$p.value)
print((wilcox.test(l_npb_LK[Relation=="Hyper"], l_npb_LK[Relation=="Mero"]))$p.value)
print((wilcox.test(l_npb_LK[Relation=="Hyper"], l_npb_LK[Relation=="RandomN"]))$p.value)
print((wilcox.test(l_npb_LK[Relation=="Mero"], l_npb_LK[Relation=="RandomN"]))$p.value)
pdf(file = "NounPhrase.pdf")
# pdf(width=8, height=6)
# boxplot(r_np_npb_KL ~ Relation, bless); title(ylab="r_np_npb_KL")
# boxplot(r_np_npb_LK ~ Relation, bless); title(ylab="r_np_npb_LK")
# boxplot(l_npb_KL     ~ Relation, bless); title(ylab="l_npb_KL")
# boxplot(l_npb_LK     ~ Relation, bless); title(ylab="l_npb_LK")
library(Hmisc)
Ecdf(r_np_npb_KL_, group=Relation, xlab=kruskalLabel(kruskal.test(r_np_npb_KL_ ~ Relation)), label.curves=list(keys=1:4), xlim=c(0,1), col=c("red","blue","purple","darkgreen"))
Ecdf(r_np_npb_LK_, group=Relation, xlab=kruskalLabel(kruskal.test(r_np_npb_LK_ ~ Relation)), label.curves=list(keys=1:4), xlim=c(0,1), col=c("red","blue","purple","darkgreen"))
Ecdf(l_npb_KL    , group=Relation, xlab=kruskalLabel(kruskal.test(l_npb_KL     ~ Relation)), label.curves=list(keys=1:4), xlim=c(0,1), col=c("red","blue","purple","darkgreen"))
Ecdf(l_npb_LK    , group=Relation, xlab=kruskalLabel(kruskal.test(l_npb_LK     ~ Relation)), label.curves=list(keys=1:4), xlim=c(0,1), col=c("red","blue","purple","darkgreen"))
dev.off()
detach(bless)
