./parse -g grammars/wmcfg/larsonian1.wmcfg -i "he matter -ed"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "David matter -ed"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "Sally matter -ed"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "I matter -ed"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "they matter -ed"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat be -s clever"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat be -s poor"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat be -s right"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat be -s young"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat be -s strange"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat be -s gentle"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat be -s long"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat be -s very clever"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "Dick matter -ed"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "Penny matter -ed"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "eggs matter -ed"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the story be -s clever"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "he doesnt matter"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the house be -s clever"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat be -s very poor"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat be -s very right"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat be -s very young"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the treat matter -ed"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the answer be -s clever"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the ticket be -s clever"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the town be -s clever"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the story be -s poor"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the story be -s right"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the story be -s young"
./parse -g grammars/wmcfg/larsonian1.wmcfg -i "the house be -s poor"
