['-ed']::[=>'Be',+case,'T'].
['-ed']::[=>'Ex',+case,'T'].
['-ed']::[=>'Have',+case,'T'].
['-ed']::[=>'Modal',+case,'T'].
['-ed']::[=>'Raise',+case,'T'].
['-ed']::[=>'V',='D',ven].
['-ed']::[=>'V',='PRO',ven].
['-ed']::[=>v,'Tc'].
['-ed']::[=>v,+case,'T'].
['-en']::[=>'Be',ven].
['-en']::[=>'V',='D',ven].
['-en']::[=>'V',='PRO',ven].
['-en']::[=>pred,ven].
['-ing']::[=>'Have',+case0,'I'].
['-ing']::[=>'Raise',ving].
['-ing']::[=>'V',='D',ving].
['-ing']::[=>'V',='D',v].
['-ing']::[=>'V',='PRO',ving].
['-ing']::[=>'V',='PRO',v].
['-ing']::[=>'V',ving].
['-ing']::[=>v,+case0,'I'].
['-ing']::[=>vf,='D',ving].
['-ll']::[='Ex','Modal'].
['-ll']::[='Neg','Modal'].
['-ll']::[=v,'Modal'].
['-ll']::[=v,+case,'T'].
['-m']::[=a,'Raise'].
['-nt']::[='Ex','Neg'].
['-nt']::[=>'Modal','Neg'].
['-nt']::[=v,'Neg'].
['-re']::[=ving,'Be'].
['-s']::['N'==>,'Num'].
['-s']::[='A','Pred'].
['-s']::[='D',+case,'Pred',-f].
['-s']::[='D',+case,'Pred'].
['-s']::[='N','Num'].
['-s']::[='Num',=poss,'D',-case].
['-s']::[=>'Be',+case,'T'].
['-s']::[=>'Have',+case,'T'].
['-s']::[=>'Modal',+case,'T'].
['-s']::[=>'N','Num'].
['-s']::[=>pred,+case,'T'].
['-s']::[=>v,+case,'T'].
['-s']::[=a,'Be'].
['-s']::[=p_in,+case,'Pred'].
['-s']::[=p_like,'Pred'].
['-s']::[=ving,'Be'].
['-s']::[v==>,+case,'T'].
['-t']::[=>'V',='D',ven].
['-ve']::[=ven,'Have'].
['a bit']::[deg].
['A']<<['Ce'].
['A']<<['D'].
['A']<<[label].
['A']<<[p_by].
['A']<<[p_in].
['A']>>['A'].
['A']>>['D'].
['A']>>['N'].
['A']>>['Pon'].
['A']>>[p_behind].
['A']>>[p_through].
['Addr']>>['C'].
['Addr']>>['Ce'].
['Adr']>>['C'].
['Adv']<<['C'].
['Adv']<<['Ce'].
['Adv']<<[p_for].
['Adv']>>['A'].
['Adv']>>['Addr'].
['Adv']>>['Adv'].
['Adv']>>['C'].
['Adv']>>['Cond1'].
['Adv']>>['Ex'].
['Adv']>>['I'].
['Adv']>>['T'].
['Adv']>>['Tm'].
['Adv']>>['V'].
['Adv']>>[a].
['Adv']>>[p_in].
['Adv']>>[p_out].
['Adv']>>[v].
['Alice']::['D',-case,-f].
['Alice']::['D',-case].
['Alice']::['N'].
['Antipathies']::['Num'].
['Australia']::['Dc'].
['Be']<<['Adv'].
['Be']<<[p_with].
['Be']<<[ving].
['C']<<['C'].
['C']<<['CR'].
['C']>>['C'].
['C']>>['V'].
['Ca']<<['CR'].
['Ca']>>['C'].
['Ca']>>['V'].
['Ca']>>[v].
['D']<<['A'].
['D']<<['Adv'].
['D']<<['QuR'].
['D']<<[p_about].
['D']<<[p_for].
['D']<<[p_from].
['D']<<[p_like].
['D']<<[p_near].
['D']<<[p_of].
['D']>>['A'].
['D']>>['C'].
['D']>>['T'].
['daisy chain']::['N'].
['Dinah']::['D',-case].
['doesnt']::[=v,+case,'T'].
['drink me']::[label].
['four thousand']::['Numl'].
['France']::['D',-case].
['I']::['D',-case].
['I']>>['C'].
['N']<<['A'].
['N']<<['CR'].
['N']<<[comp].
['N']<<[label].
['N']<<[p_about].
['N']<<[p_for].
['N']<<[p_of].
['N']<<[p_under].
['N']<<[p_with].
['N']>>['N'].
['Neg']>>[deg].
['New Zealand']::['Dc'].
['Nml']>>['A'].
['Nml']>>['N'].
['Num']<<[p_in].
['Numl']>>['N'].
['Numl']>>['Num'].
['oh dear']::[exclam].
['Pout']>>['N'].
['Pred']<<['Adv'].
['Pred']<<['Ce'].
['Pred']<<['Pdown'].
['Pred']<<[p_for].
['Pred']<<[tmp].
['Qu']>>['N'].
['s']::[='Num',='D','D'].
['s']::[='Num',=poss,'D',-case].
['such as']::['Adv'].
['T']<<['Adv'].
['T']<<['C'].
['T']<<['CR'].
['T']<<[p_for].
['T']<<[tmp].
['T']>>[ving].
['that']::['D',-case].
['that']::['D'].
['V']<<['Adv'].
['V']<<['C'].
['V']<<['Ce'].
['V']<<['D'].
['V']<<['Pat'].
['V']<<['Pclose'].
['V']<<['Pin'].
['V']<<[deg].
['V']<<[l_like].
['V']<<[manner].
['V']<<[p].
['V']<<[p_at].
['V']<<[p_by].
['V']<<[p_down].
['V']<<[p_for].
['V']<<[p_from].
['V']<<[p_into].
['V']<<[p_in].
['V']<<[p_in].
['V']<<[p_like].
['V']<<[p_onto].
['V']<<[p_on].
['V']<<[p_past].
['V']<<[p_through].
['V']<<[p_to].
['V']<<[p_upon].
['V']<<[p_with].
['V']<<[tmp].
[about]::['A'].
[about]::[='D',+case,'Pabout'].
[about]::[=p_among,'Pabout'].
[about]::[deg].
[across]::[='D',+case,'Pacross'].
[actually]::['Adv'].
[advice]::['N'].
[advise]::[='Ce',='D',+case,'V'].
[afraid]::[='Ce','A'].
[afterwards]::[tmp].
[after]::[='C',tmp].
[after]::[='D',+case,'Pafter'].
[against]::[='D',+case,'Pagainst'].
[again]::[tmp].
[air]::['N'].
[all]::['D',-case].
[all]::['Qu'].
[all]::['QuR'].
[all]::[='D','Q'].
[all]::[='D','Qu'].
[all]::[='D',+case,'Deg'].
[all]::[deg].
[almost]::[deg].
[along]::[='D',+case,'Palong'].
[aloud]::['Adv'].
[always]::[deg].
[among]::[='D',+case,'Pamong'].
[and]::[='A',='A','A'].
[and]::[='C',='C','C'].
[and]::[='Ce',='Ce','Ce'].
[and]::[='D',='D','D'].
[and]::[='Dc',='Dc','D',-case].
[and]::[='I',='I','I'].
[and]::[='N',='N','N'].
[and]::[='Num',='Num','Num'].
[and]::[='T',='T','T'].
[and]::[='Tc',='Tc',+case,'T'].
[and]::[=p_down,=p_up,p_down].
[and]::[=p_up,=p_down,p_down].
[and]::[=vc,=v,v].
[and]::[=vc,=vc,vc].
[and]::[conj].
[answer]::[='D',+case,'V'].
[anxiously]::['Adv'].
[anything]::['D',-case].
[any]::['Adv'].
[any]::[='Num','D',-case].
[any]::[=p_of,'D',-case].
[an]::[='Num','D',-case].
[are]::[=p_in,+case,'Raise'].
[ask]::[='Ce',='D',+case,'V'].
[ask]::[='D',+case,'V'].
[as]::[='D',+case,'As'].
[as]::[='T','C'].
[as]::[='T','Ca'].
[as]::[='T','Ce'].
[as]::[='T',comp].
[as]::[conj].
[as]::[deg].
[ate]::[='D',+case,'V'].
[at]::[='D',+case,'Pat'].
[at]::[=tmp,'Pat'].
[away]::['Paway',-f].
[away]::['Paway'].
[a]::[='Num','D',-case].
[a]::[='Num','D'].
[a]::[='Q','D',-case].
[a]::[mod].
[back]::[=p_to,'Pback'].
[bank]::['N'].
[bat]::['N'].
[beast]::['N'].
[beautifully]::['Adv'].
[because]::[conj].
[bed]::[=p_of,'N'].
[been]::[=ving,'Been'].
[been]::[=ving,ven].
[before]::[='D',+case,'Pbefore'].
[before]::[tmp].
[began]::['V'].
[began]::[='T', 'V'].
[begin]::[='Ce', 'Raise'].
[begin]::[='Ce','V'].
[begun]::[='T', 'V'].
[behind]::[='D',+case,'Pbehind'].
[belong]::[=p_to,'V'].
[best]::['N'].
[be]::[='A','Be'].
[be]::[='D','Pred'].
[be]::[='D',+case,'Pred'].
[be]::[=a,'Be'].
[be]::[=a,'Pred'].
[be]::[=p_down,'Be'].
[be]::[=p_like,'Pred'].
[be]::[=p_of,'Be'].
[be]::[=p_up,'Be'].
[be]::[=v,'Be'].
[be]::[=ving,'Be'].
[bit]::['N'].
[bleed]::['V'].
[blown]::[='Pout','V'].
[bookshelf]::['N'].
[book]::[=p_of,'N'].
[book]::[=p_without,'N'].
[bottle]::['N'].
[box]::['N',-f].
[box]::['N'].
[box]::[='D',+case,'V'].
[brave]::['A',-wh].
[brave]::['A'].
[brighten]::[=p_at,='Pup','V'].
[bright]::['A'].
[bring]::[=p_into,='D',+case,'V'].
[burnt]::[='D','V'].
[burn]::['V'].
[burn]::[='D',+case,'V'].
[buttered]::['A'].
[but]::[='C',='C','C'].
[but]::[conj].
[by]::['Pby'].
[by]::[='D',+case,'Pby'].
[cake]::['N'].
[came]::[=p_upon,'V'].
[candle]::['N'].
[can]::[=v,'Modal'].
[care]::[='Ce','V'].
[catch]::[='D',+case,'V'].
[cat]::['N'].
[center]::[=p_of,'N'].
[certainly]::['Adv'].
[certain]::[='Ce','A'].
[cheat]::[=p_in,='D',+case,'V'].
[cherry]::['A'].
[child]::['N'].
[close]::['A'].
[close]::[='Pby','Pclose'].
[come]::[='Pout','V'].
[come]::[=p_to,'V'].
[come]::[exclam].
[conjoin]::['C'].
[conjoin]::['T'].
[conj]>>['C'].
[conj]>>['Ca'].
[conj]>>['Cond1'].
[conj]>>['CR'].
[conj]>>['D'].
[consider]::[='C', 'V'].
[consider]::[='Ce','V'].
[conversation]::['N'].
[cool]::['A'].
[corner]::['N'].
[could]::[='Neg','Modal'].
[could]::[=v,'Modal'].
[country]::['N'].
[cpright]::['C'].
[creep]::[=p_under,'V'].
[croquet]::['N'].
[cry]::['V'].
[cupboard]::['N'].
[curiosity]::['N'].
[curious]::['A'].
[currant]::['N'].
[curtsey]::['V'].
[custard]::['N'].
[cut]::[='D',+case,'V'].
[daisy]::['N'].
[dark]::['A'].
[day]::['N'].
[decide]::[=p_on,'V'].
[deeply]::['Adv'].
[deep]::['A'].
[deg]>>['A'].
[deg]>>['Adv'].
[deg]>>['D'].
[deg]>>['Nml'].
[deg]>>['Qu'].
[deg]>>['V'].
[deg]>>[conj].
[deg]>>[p_down].
[deg]>>[p_in].
[deg]>>[p_like].
[deg]>>[p_round].
[deg]>>[p_up].
[deg]>>[tmp].
[delight]::['N'].
[did]::[='Neg',+case,'T'].
[did]::[=v,+case,'T'].
[dip]::[='Pdown','V'].
[disagree]::[=p_with,'V'].
[disappointment]::['N'].
[distance]::['N'].
[doorway]::['N'].
[door]::['N'].
[downward]::['A'].
[down]::['A'].
[down]::['Pdown',-f].
[down]::['Pdown'].
[down]::[='D',+case, 'Pdown'].
[down]::[='D',+case,'Pdown'].
[down]::[=p_after, 'Pdown',-f].
[down]::[=p_after, 'Pdown'].
[do]::['V'].
[do]::[='D','V'].
[do]::[='D',+case,'V'].
[do]::[='Neg',+case,'T'].
[do]::[=v,+case,'T'].
[dreamy]::['A'].
[dream]::['V'].
[dream]::[='Ce','V'].
[drink]::[='D',+case,'V'].
[drop]::[='D',+case,'V'].
[dry]::['A'].
[d]::['D'].
[earnestly]::['Adv'].
[earth]::['N'].
[ear]::['N'].
[eaten]::[=p_up,'V'].
[eat]::[='D',+case,'V'].
[eat]::[label].
[either]::['Adv'].
[either]::[conj].
[else]::['A'].
[empty]::['A'].
[end]::['N'].
[end]::[=p_in,'V'].
[enough]::[=p_of,'A'].
[even]::['Adv'].
[ever]::['Adv'].
[ever]::[tmp].
[except]::[='D',+case,'Pexcept'].
[exclam]>>['Addr'].
[exclam]>>['C'].
[exclam]>>['Ce'].
[exclam]>>['CQ'].
[eye]::['N'].
[face]::['N'].
[fact]::['N'].
[fact]::[='Ce','N'].
[fall]::['N'].
[fall]::['V'].
[fall]::[=p_down, 'V'].
[fall]::[=p_through,'V'].
[fancy]::[='Ce','V'].
[fancy]::[='D',+case,'V'].
[fear]::[=p_of,'N'].
[feeling]::['N'].
[feel]::[='Ce','V'].
[feel]::[=a, +case,'V'].
[feet]::['N'].
[fell]::['V'].
[fell]::[=p_off,'V'].
[fell]::[=p_on,'V'].
[felt]::[='Ce','V'].
[felt]::[=a,'V'].
[few]::[='Num', 'Q'].
[few]::[='Num','Qu'].
[field]::['N'].
[fifteen]::['Nml'].
[filled]::[=p_with,'A'].
[filler]::[p_by].
[find]::[='Ce','V'].
[find]::[='D',+case,'V'].
[find]::[=a,+case,'V'].
[find]::[=p_on,='D',+case,'V'].
[finger]::['N'].
[finish]::[='Poff','V'].
[first]::['A'].
[first]::[tmp].
[fit]::['V'].
[flame]::['N'].
[flash]::[=p_across,'V',-f].
[flavor]::['N'].
[flavor]::[=p_of,'N'].
[flower]::['N'].
[follow]::[='D',+case,'V'].
[fond]::[=p_of,'A'].
[forgot]::[='Ce','V'].
[forgot]::[='D',+case,'V'].
[fortunately]::['Adv'].
[for]::[='D',+case,'Pfor'].
[for]::[='T','C'].
[for]::[p_for].
[found]::[='Ce','V'].
[found]::[='D',+case,'V'].
[found]::[=p_in,='D',+case,'V'].
[found]::[=p_on,='D',+case,'V'].
[found]::[=v,+case,'V'].
[fountain]::['N'].
[friend]::['N'].
[from]::[='D',+case,'Pfrom'].
[funny]::['A'].
[further]::['Adv'].
[game]::['N'].
[game]::[=p_of,'N',-f].
[garden]::['N'].
[gave]::[=p_to,='D',+case,'V'].
[generally]::['Adv'].
[get]::[='a','Get'].
[get]::[='A','Raise'].
[get]::[='D',+case,'V'].
[get]::[='Pout','V'].
[get]::[='Pup','V'].
[get]::[=a,'Raise'].
[get]::[=p_into,'V'].
[get]::[=p_out,'Raise'].
[get]::[=p_out,'V'].
[get]::[=p_through,+case,'V'].
[girl]::['N'].
[glad]::['A'].
[glad]::[='Ce','A'].
[glass]::['A'].
[glass]::['N'].
[going]::[='T', 'V'].
[golden]::['A'].
[good]::['A'].
[got]::[=p_to,'V'].
[go]::[='Ce','V'].
[go]::[='Pout','V'].
[go]::[='T','V'].
[go]::[=p_into,'V'].
[go]::[=p_into,=p_through,'V'].
[go]::[=p_through,'V'].
[grand]::['A'].
[great]::['A'].
[grow]::[='A','V'].
[grow]::[='D',+case,'V'].
[had]::[='Been','Have'].
[had]::[='D',+case,'V'].
[had]::[='Neg','Have'].
[had]::[='Order','Have'].
[had]::[=ven,'Have'].
[half]::['Adv'].
[half]::['V'].
[hall]::['N'].
[hand]::['N'].
[happen]::['V'].
[hardly]::['Adv'].
[have]::[='Been','Have'].
[have]::[='D',+case,'V'].
[have]::[='T','V'].
[have]::[=ven,'Have'].
[head]::['N'].
[heap]::[=p_of,'N'].
[hear]::[='Ce','V'].
[hedge]::['N'].
[here] :: ['D',-case].
[here]::['D',-case].
[here]::[tmp].
[herself]::['D',-case].
[her]::['D',-case].
[her]::[='Num','D',-case].
[he]::['D',-case].
[high]::['A'].
[history]::['N'].
[hold]::[='D',+case,'V'].
[hold]::[=p_on,='D',+case,'V'].
[hole]::['N'].
[home]::['N'].
[hope]::[='Ce','V'].
[hot]::['A'].
[house]::['N'].
[however]::['Adv'].
[how]::['Adv',-wh].
[how]::['Adv'].
[how]::[='Num','D',-case,-wh].
[how]::[deg,-wh].
[how]::[deg].
[how]::[how].
[how]::[manner].
[how]<<[p_in].
[hung]::[=p_upon,'A'].
[hurry]::['N'].
[hurry]::[=p_down,'V'].
[hurt]::['A'].
[idea]::[='C','N'].
[idea]::[='Ce','N'].
[if]::[='T','Ce'].
[if]::[='T','Cond1',-f].
[if]::[='T','CR'].
[if]::[='T',cond1,-f].
[if]::[='T',cond].
[ignorant]::['A'].
[impossible]::['A'].
[inch]::['N'].
[indeed]::['Adv'].
[inter]>>['C'].
[inter]>>['Ce'].
[inter]>>['T'].
[into]::[='D',+case,'Pinto'].
[in]::[='D','Pin'].
[in]::[='D',+case,'Pin'].
[is]::[='A','Be'].
[is]::[='Ce','Pred'].
[is]::[='D',+case,'Pred'].
[is]::[=p_like,'Pred'].
[is]::[=v,'Be'].
[itself]::['D',-case].
[it]::['D',-case,-f].
[it]::['D',-case].
[it]::['D'].
[jar]::['N'].
[just]::['Adv'].
[just]::[deg].
[just]::[tmp].
[key]::['N'].
[kill]::[='D',+case,'V'].
[knelt]::[='Pdown','V'].
[knew]::[='Ce','V'].
[knife]::['N'].
[knowledge]::['N'].
[know]::[='Ce','V'].
[labelled]::[='N','A'].
[label]::['N'].
[label]<<[labelR].
[larger]::['A'].
[larger]::[=p_than,'A'].
[large]::['A'].
[lately]::[tmp].
[later]::[tmp].
[late]::['A',-wh].
[late]::['A'].
[latitude]::['N'].
[leaf]::['N'].
[learn]::[='D',+case,'V'].
[led]::[=p_into,'V'].
[left]::['A'].
[leg]::['N'].
[lesson]::['N'].
[letter]::['N'].
[let]::[='Ce','V'].
[lie]::[=p_under,'V'].
[likely]::['Adv'].
[like]::[='Ce','V'].
[like]::[='D',+case,'Plike'].
[like]::[='D',+case,like].
[listen]::['V'].
[listen]::[=p_to,'V'].
[little]::['A'].
[little]::[deg].   
[lit]::[='Pup','A'].
[locked]::['A'].
[lock]::['N'].
[longer]::[tmp].
[longitude]::['N'].
[long]::['A'].
[long]::['Adv'].
[long]::[='Ce','V'].
[look]::['V'].
[look]::[='Pdown','V'].
[look]::[=p_about,'V'].
[look]::[=p_at,'V'].
[look]::[=p_into,=p_along,'V'].
[lost]::[='D','V'].
[loveliest]::['A'].
[lovely]::['A'].
[low]::['A'].
[maam]::['Adr'].
[made]::[='V',='D',v].
[made]::[=p_of,'A'].
[make]::[='Ce',='D',+case,'V'].
[make]::[='D',+case,'V'].
[make]::[=p_out,'V'].
[make]::[=p_out,'Vc'].
[manage]::[='Ce','V'].
[manage]::[='D',+case,'V'].
[manner]<<[p_in].
[many]::['Qu'].
[many]::[='Num','Num'].
[map]::['N',-f].
[map]::['N'].
[marked]::['A'].
[marked]::[='N','A'].
[marked]::[=p_on,'A'].
[marmalade]::['N'].
[matter]::['V'].
[me]::['D',-case].
[me]::[labelR].
[mice]::['N'].
[middle]::['N'].
[might]::[=v,'Modal'].
[mile]::['N'].
[milk]::['N'].
[mind]::['N'].
[minute]::['N'].
[miss]::[='D',+case,'V'].
[mixed]::['A'].
[mod]>>[deg].
[moment]::['N',-f].
[moment]::['N'].
[more]::['A'].
[mouse]::['N'].
[much]::['Adv'].
[much]::['D',-case].
[much]::[deg].
[must]::[='Be','Modal'].
[name]::['N'].
[name]::[=p_of,'N'].
[natural]::['A'].
[near]::[='D',+case,'Pnear'].
[neck]::[=p_of,'N'].
[nervous]::[=p_about,'A'].
[never]::[='Ex','Neg'].
[never]::[=v,'Neg'].
[never]::[=ven,'Neg'].
[never]::[tmp].
[next]::[tmp].
[nice]::['A'].
[nor]::[conj].
[nothing]::['D',-case].
[nothing]::['N'].
[nothing]::[=p_of,'N'].
[notice]::[='Ce','V'].
[notice]::[='D',+case,'V'].
[not]::['Adv'].
[not]::['Neg'].
[not]::[='Ce','Neg'].
[not]::[='V', 'Neg'].
[not]::[=>pred,'Neg'].
[not]::[=>v,'Neg'].
[not]::[=a,'Neg'].
[not]::[=pred,'Neg'].
[not]::[=v,'Neg'].
[not]::[=ven,'Neg'].
[not]::[=ving, 'Neg'].
[now]::['Adv'].
[now]::[exclam].
[now]::[tmp].
[no]::[='CRel','D',-case].
[no]::[='Num','D',-case].
[no]::[=tmp, 'Neg'].
[no]::[exclam].
[no]::[inter].
[occur]::[=p_to,'V',-f].
[off]::['Poff'].
[off]::[='D',+case,'Poff'].
[of]::[='D',+case,'Pof'].
[oh]::[='D',+case,inter].
[oh]::[exclam].
[once]::[tmp].
[once]::[tmp].
[one]::['D',-case].
[one]::['N'].
[one]::['Nml'].
[one]::[=p_of,'D',-case].
[only]::['Adv'].
[only]::[deg].
[onto]::[='D',+case,'Ponto'].
[on]::['Pon'].
[on]::[='D',+case,'Pon'].
[on]::[=ving,'Pon'].
[open]::[='D',+case,'V'].
[opportunity]::[=p_for,'N'].
[orange]::['N'].
[or]::[='A',='A','A'].
[or]::[='C',='C','C'].
[or]::[='Ce',='Ce','Ce'].
[or]::[='D',='Tc','Tc'].
[or]::[='Dc',='Dc','D',-case].
[or]::[='Num',='Num','Num'].
[or]::[='Tc',='Tc','T'].
[or]::[=tmp, =tmp,tmp].
[or]::[=tmp,=tmp,tmp].
[or]::[conj].
[other]::['N'].
[ought]::[='T','V'].
[out]::['Pout'].
[out]::[='Ce',=p_of,'Pout'].
[out]::[='D','Pout'].
[out]::[='D',+case,'Pout'].
[out]::[=p_of, 'Pout'].
[out]::[=p_of,'Pout'].
[overhead]::['Adv'].
[over]::['A'].
[over]::[='D',+case,'Pover'].
[own]::['A'].
[paper]::['N'].
[passage]::['N'].
[pass]::['V'].
[past]::[='D',+case,'Ppast'].
[peg]::['N'].
[people]::['N'].
[people]::['N'].     [people]::['N', -f].
[perhaps]::['Adv'].
[person]::['N'].
[pick]::[='D',+case,'V'].
[picture]::['N',-f].
[picture]::['N'].
[pineapple]::['N'].
[pink]::['A'].
[plainly]::['Adv'].
[play]::[=p_against,='D',+case,'V'].
[please]::[inter].
[pleasure]::['N'].
[pleasure]::[=p_of,'N'].
[plenty]::['D',-case].
[pocket]::['N'].
[poison]::['N'].
[poison]::[label].
[poker]::['N'].
[poor]::['A'].
[pop]::[=p_down, 'V'].
[possibly]::['Adv'].
[practice]::['N',-f].
[practice]::['N'].
[presently]::[tmp].
[pretend]::[='Ce','V'].
[printed]::[=p_on,'A'].
[put]::[='D',+case,'V'].
[put]::[=p_into,='D',+case,'V'].
[p_about]>>['A'].
[p_across]>>['V'].
[p_after]>>['C'].
[p_after]>>['T'].
[p_at]>>['C'].
[p_at]>>['D'].
[p_at]>>['Dc'].
[p_at]>>['T'].
[p_for]>>['V'].
[p_in]>>['Adv'].
[p_in]>>['C'].
[p_in]>>['V'].
[p_of]<<[p_without].
[p_on]<<[p_except].
[p_on]>>['T'].
[p_to]>>['T'].
[question]::['N'].
[quite]::['Adv'].
[quite]::[deg].
[rabbit]::['N'].
[ran]::['V'].
[rathole]::['N'].
[rate]::['N'].
[rather]::['Adv'].
[rather]::[deg].
[reach]::[='D',+case,'V'].
[read]::[='D',+case,'V'].
[really]::[deg].
[redhot]::['A'].
[remain]::[='D',+case,'V'].
[remarkable]::['A'].
[remember]::[='D',+case,'V'].
[respectable]::['A'].
[right]::['A'].
[roast]::['A'].
[room]::['N'].
[round]::['A'].
[round]::[='D',+case,'Pround'].
[rule]::['N'].
[sadly]::['Adv'].
[said]::[='Ce','V'].
[said]::[='Ce',=p_to,'V'].
[said]::[='CeF',=p_to,'V'].
[same]::['A'].
[sat]::[='Pdown','V'].
[saucer]::['N'].
[saw]::[='D',+case,'V'].
[say]::[='C','V'].
[say]::[='Ce','V'].
[say]::[='Ce',=p_to,'V'].
[say]::[='CQ','V'].
[say]::[='D',+case,'V'].
[say]::[='Pover','V'].
[school]::['N'].
[scold]::[='D',+case,'V'].
[second]::['A'].
[seem]::[='Order','Raise'].
[seem]::[='T','Raise'].
[seem]::[=a,'Raise'].
[seen]::[='D','V'].
[see]::['V'].
[see]::[='Ce','V'].
[see]::[='D',+case,'V'].
[seldom]::['Adv'].
[several]::[='Num','D',-case].
[severely]::['Adv'].
[shall]::[='Be','Modal'].
[shall]::[=v,'Modal'].
[sharply]::['Adv'].
[shelf]::['N'].
[she]::['D',-case,-f].
[she]::['D',-case].
[shoulder]::['N'].
[should]::[='Pred','Modal'].
[should]::[=v,'Modal'].
[show]::[=p_off,'V'].
[shrink]::['V'].
[shut]::[='Pup','V'].
[side]::['N'].
[sight]::['N'].
[simple]::['A'].
[sister]::['N'].
[sit]::['V'].
[size]::['N'].
[sleepy]::['A'].
[slightest]::['A'].
[slippery]::['A'].
[slowly]::['Adv'].
[smaller]::['A'].
[small]::['A'].
[somebody]::['D',-case].
[sometimes]::[tmp].
[somewhere]::['D',-case].
[somewhere]::['D'].
[some]::[='Num','D',-case].
[sooner]::[tmp].
[soon]::[tmp].
[sort]::['N'].
[sort]::[=p_of,'N'].
[sound]::[='D',+case,'V'].
[so]::['Adv'].
[so]::[='T','C'].
[so]::[conj].
[so]::[deg].
[spoke]::['V'].
[stair]::['N'].
[stick]::['N'].
[still]::['Adv'].
[still]::[tmp].
[stop]::[='D',+case,'V'].
[straight]::['A'].
[stupid]::['A'].
[such]::['A'].
[such]::[deg].
[suddenly]::['Adv'].
[suddenly]::[tmp].
[sure]::['A'].
[surprised]::[='Ce','A'].
[table]::['N'].
[take]::[='Pout',='D',+case,'V'].
[talk]::['V'].
[tart]::['N'].
[taste]::[='D',+case,'V'].
[taught]::[=p_to,='D',+case,'V'].
[tc]::['Tc'].
[teatime]::['N'].
[tear]::['N'].
[telescope]::['N'].
[tell]::[='D',+case,'V'].
[tell]::[=p_to,='D',+case,'V'].
[tell]::[=p_tod,='D',+case,'V'].
[temporary]::['Ce'].
[ten]::[='Num','Nml'].
[test]::['Ce'].
[than]::[='D',+case,'Pthan'].
[that]::['D',-case].
[that]::[='T','Ce'].
[them]::['D',-case].
[then]::['Adv'].
[then]::[tmp].
[there]::['D',-case].
[there]::['D'].
[they]::['D',-case].
[the]::[='Num','D',-case].
[the]::[='Num','D'].
[thing]::['N',-f].
[thing]::['N'].
[think]::[='Ce','V'].
[think]::[='D',+case,'V'].
[think]::[='Pred','V'].
[think]::[=p_about,='D',+case,'V'].
[think]::[=p_to,='D',+case,'V'].
[this]::['D',-case].
[this]::[='Num','D',-case].
[thought]::['N'].
[thought]::[='Ce','N'].
[thought]::[='Ce','V'].
[thought]::[='Ce',=p_to,'V'].
[thought]::[='Order','V'].
[thought]::[=p_over,'V'].
[though]::[conj].
[threelegged]::['A'].
[through]::[='D',+case,'Pthrough'].
[through]::[='D',+case0,'Pthrough'].
[thump]::[inter].
[time]::['N'].
[time]::[='Ce','N'].
[tiny]::['A'].
[tired]::['A'].
[tired]::[='p_of','A'].
[tire]::[=p_out,'V'].
[tmp]>>['C'].
[tmp]>>['I'].
[tmp]>>['Pred'].
[tmp]>>['T'].
[tmp]>>['V'].
[tmp]>>[pred].
[tmp]>>[p_in].
[tmp]>>[ven].
[tmp]>>[v].
[toast]::['N'].
[toffee]::['N'].
[together]::['Adv'].
[tonight]::[tmp].
[took]::[='Pout',='D',+case,'V'].
[too]::[deg].
[top]::[=p_of,'N'].
[to]::[='Be','T'].
[to]::[='Be',+case,'T'].
[to]::[='D',+case,'Pto'].
[to]::[='Get',+case0,'T'].
[to]::[='Have',+case0,'T'].
[to]::[=v,'T'].
[to]::[=v,+case0,'T'].
[trouble]::['N'].
[trouble]::[=p_of,'N'].
[true]::['A'].
[truth]::['N'].
[try]::['V'].
[try]::[='Ce','V'].
[try]::[='D',+case,'V'].
[try]::[='T', 'V'].
[tumble]::[=p_down,'V'].
[tunnel]::['N'].
[turkey]::['N'].
[turn]::[='D',+case,'V'].
[twice]::[tmp].
[two]::['Numl'].
[under]::[='D',+case,'Punder'].
[unpleasant]::['A'].
[upon]::[='D',+case,'Pupon'].
[up]::['Pup'].
[up]::[='D','Pup'].
[up]::[='D',+case,'Pup'].
[use]::['N'].
[use]::[=p_of,'N'].
[usually]::[tmp].
[venture]::[='Ce','V'].
[very]::[deg].
[v]<<['Adv'].
[v]<<[p_among].
[v]<<[p_with].
[v]>>['T'].
[waistcoat]::['N'].
[wait]::['V'].
[wait]::[='T', 'V'].
[walk]::['V'].
[wander]::[='Pabout','V'].
[was]::['Pred'].
[was]::[='Ce','Be'].
[was]::[='Ce','Pred'].
[was]::[='D',+case,'Pred',-f].
[was]::[='D',+case,'Pred'].
[was]::[='D',+case,'Raise'].
[was]::[='Neg','Be'].
[was]::[='Neg','T'].
[was]::[='Neg',+case,'T'].
[was]::[='Order','Be'].
[was]::[=a,'Be'].
[was]::[=a,'Pred'].
[was]::[=a,'Raise'].
[was]::[=a,+case,'Be'].
[was]::[=neg,'Be'].
[was]::[=p_before,'Be'].
[was]::[=p_behind,'Pred'].
[was]::[=p_in,'Be'].
[was]::[=p_in,'Pred'].
[was]::[=p_on,+case,'Be'].
[was]::[=p_round,'Be'].
[was]::[=v,+case,'Raise'].
[was]::[=ving,'Be'].
[watch]::['N', -f].
[watch]::['N'].
[way]::['N'].
[well]::['A',-f].
[well]::['N'].
[well]::[=comp,'Adv'].
[well]::[exclam].
[well]::[inter].
[went]::[='Paway','V'].
[went]::[='Pdown','V'].
[went]::[='Pon','V'].
[went]::[=>p_down,'V'].
[went]::[=p_back,'V'].
[went]::[=p_down,'V'].
[went]::[=p_down,+f,'V'].
[went]::[=p_for,=p_back,'V'].
[were]::[='a','Be'].
[were]::[='D',+case,'Pred'].
[were]::[=a,'Be'].
[were]::[=a,'Pred'].
[were]::[=p_round,+case,'Be'].
[what]::['D',-case,-wh].
[what]::[deg].
[when]::[='Order','C'].
[when]::[='Order','Ca'].
[when]::[='T','C'].
[when]::[='T','CR'].
[when]::[='T',+f,'C'].
[whether]::['Ce'].
[whether]::[='T','Ce'].
[which]::['D',-case,-f].
[which]::['D',-case].
[which]::[='Num',+f,'D',-case,-wh].
[while]::['N'].
[whisker]::['N'].
[white]::['A'].
[why]::[inter].
[wild]::['A'].
[will]::[='Be','Modal'].
[will]::[='Have','Modal'].
[will]::[='V','Modal'].
[will]::[=v,'Modal'].
[wind]::['N'].
[wise]::['A'].
[wish]::[='Ce','V'].
[without]::[='D',+case,'Pwithout'].
[without]::[=p_in,+case, 'Pwithout'].
[with]::[='D',+case, 'Pwith'].
[with]::[='D',+case,'Pwith'].
[wonder]::[='Ce','V'].
[wonder]::[=p_at,'V'].
[word]::['N'].
[world]::['N'].
[would]::[='Be','Modal'].
[would]::[='Neg','Modal'].
[would]::[=pred,'Modal'].
[would]::[=v,'Modal'].
[yay]::['CR'].
[yesterday]::[tmp]. [today]::[tmp].
[yes]::[inter].
[young]::['A'].
[you]::['D',-case,-f].
[you]::['D',-case].
[]::['A'].
[]::['Ce'].
[]::['D',-case].
[]::['PRO',-case0].
[]::['V'].
[]::[='A',='Ce',a].
[]::[='A',='D',a].
[]::[='A',='PRO',a].
[]::[='A',='Qu',a].
[]::[='Adv','F'].
[]::[='Ce', ='Neg',neg].
[]::[='Ce','Order'].
[]::[='Ce',+f,'CeF'].
[]::[='Ce',='Ce','Ce'].
[]::[='Cond2',='Cond1',cond].
[]::[='D',+case,'Addr'].
[]::[='D',+case,'P'].
[]::[='D',+case,'Pred'].
[]::[='D',+case,poss].
[]::[='Modal',+case,'T'].
[]::[='N','Num'].
[]::[='N',='N','N'].
[]::[='Num','D',-case].
[]::[='Num',+f,'D',-case,-wh].
[]::[='Order','C'].
[]::[='Order',cond].
[]::[='P',p].
[]::[='Pout',p_out].
[]::[='Pred',='D',pred].
[]::[='Qu','D',-case].
[]::[='T','C'].
[]::[='T','Ca'].
[]::[='T','Ce',-f].
[]::[='T','Ce'].
[]::[='T','Cond2'].
[]::[='T','CR'].
[]::[='T','Order'].
[]::[='T',+f,'C'].
[]::[='T',+f,'Order'].
[]::[='T',+wh,'C'].
[]::[='T',+wh,'Ce'].
[]::[='T',+wh,'CQ',-f].
[]::[='T',cond].
[]::[='V',+f,'Order'].
[]::[='V',v].
[]::[=>'A',='D',a].
[]::[=>'As',comp].
[]::[=>'Be',+case,'T'].
[]::[=>'Be',='D','Ex'].
[]::[=>'Be',='D',pred].
[]::[=>'Be',='D',v].
[]::[=>'Deg',deg].
[]::[=>'Ex',+case,'T'].
[]::[=>'Have',+case,'T'].
[]::[=>'Have',+case,'Tc'].
[]::[=>'Modal',+case,'T'].
[]::[=>'N','Num'].
[]::[=>'Neg',+case,'T'].
[]::[=>'Pabout',p_about].
[]::[=>'Pacross',p_across].
[]::[=>'Pafter',p_after].
[]::[=>'Pagainst',p_against].
[]::[=>'Palong',p_along].
[]::[=>'Pamong',p_among].
[]::[=>'Pat',p_at].
[]::[=>'Pback',p_back].
[]::[=>'Pbefore',='D',p_before,-f].
[]::[=>'Pbefore',='D',p_before].
[]::[=>'Pbehind',='D',p_behind].
[]::[=>'Pbehind',p_behind,-f].
[]::[=>'Pby',p_by].
[]::[=>'Pdown',='D',p_down].
[]::[=>'Pdown',p_down].
[]::[=>'Pexcept',p_except].
[]::[=>'Pfor',p_for].
[]::[=>'Pfrom',p_from].
[]::[=>'Pin',='D',p_in].
[]::[=>'Pin',p_in].
[]::[=>'Pinto',p_into].
[]::[=>'Plike',='D',p_like].
[]::[=>'Plike',p_like].
[]::[=>'Pnear',p_near].
[]::[=>'Pof',='D',p_of].
[]::[=>'Pof',='Num',p_of].
[]::[=>'Pof',p_of].
[]::[=>'Poff',p_off].
[]::[=>'Pon',='D',p_on].
[]::[=>'Pon',p_on,-f].
[]::[=>'Pon',p_on].
[]::[=>'Ponto',p_onto].
[]::[=>'Pout',='D',p_out].
[]::[=>'Pout',p_out].
[]::[=>'Pover',+f,p_over].
[]::[=>'Pover',p_over].
[]::[=>'Ppast',p_past].
[]::[=>'Pred',+case,'T'].
[]::[=>'Pred',='Ce',pred].
[]::[=>'Pred',='D','Ex'].
[]::[=>'Pred',='D',pred].
[]::[=>'Pred',='PRO',pred].
[]::[=>'Pround',='D',p_round,-f].
[]::[=>'Pround',='D',p_round].
[]::[=>'Pthan',p_than].
[]::[=>'Pthrough',='D',p_through].
[]::[=>'Pthrough',p_through].
[]::[=>'Pto',p_to,-f].
[]::[=>'Pto',p_to].
[]::[=>'PtoD',p_tod].
[]::[=>'Punder',p_under].
[]::[=>'Pup',='D',p_up].
[]::[=>'Pup',p_up].
[]::[=>'Pupon',p_upon].
[]::[=>'Pwith',p_with].
[]::[=>'Pwithout',p_without,-move].
[]::[=>'Pwithout',p_without].
[]::[=>'Raise',+case,'T'].
[]::[=>'Raise',='D','Ex'].
[]::[=>'T','Ce'].
[]::[=>'T',+f,'C'].
[]::[=>'T',+f,'Order'].
[]::[=>'V',+case,'T'].
[]::[=>'V',+pass,v].
[]::[=>'V',='Ce',v].
[]::[=>'V',='D',+f,v].
[]::[=>'V',='D',ven].
[]::[=>'V',='D',v].
[]::[=>'V',='PRO',v].
[]::[=>'V',='Q',v].
[]::[=>'V',='Qu',v].
[]::[=>'V',vc].
[]::[=>inter,'C'].
[]::[=>inter,exclam].
[]::[=>like,l_like].
[]::[=>pred,+case,'T'].
[]::[=>pred,+f,'Ex'].
[]::[=>pred,='D','T'].
[]::[=>pred,='D',+f,'Ex'].
[]::[=>v, ='D','Ex'].
[]::[=>v,'Order'].
[]::[=>v,'T'].
[]::[=>v,'Tc'].
[]::[=>v,+case,'T',-f].
[]::[=>v,+case,'T'].
[]::[=>v,+case,+f,'T'].
[]::[=>v,+case0,'T'].
[]::[=>v,='D','Ex'].
[]::[=>v,='D',+f,'Ex'].
[]::[=>ving,+case,'T'].
[]::[=>ving,+case0,'T'].
[]::[=>vpass,+case,'T'].
[]::[=>vpass,+case,'Tc'].
[]::[=a,+case,'Pred'].
[]::[=a,+f,'Order'].
[]::[=cond,'Ce'].
[]::[=cond,=cond,cond].
[]::[=cond2,=cond1,cond].
[]::[=pred,+case,'T'].
[]::[=p_out,+case,'Pred'].
[]::[=vc,='PRO',v].
[]::[=ving,+case0,'T'].
startCategory('C').
startCategory('F').
