./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "he matter -ed"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "David matter -ed"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "Sally matter -ed"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "I matter -ed"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "they matter -ed"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat be -s clever"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat be -s poor"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat be -s right"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat be -s young"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat be -s strange"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat be -s gentle"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat be -s long"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat be -s very clever"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "Dick matter -ed"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "Penny matter -ed"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "eggs matter -ed"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the story be -s clever"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "he doesnt matter"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the house be -s clever"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat be -s very poor"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat be -s very right"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat be -s very young"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the treat matter -ed"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the answer be -s clever"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the ticket be -s clever"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the town be -s clever"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the story be -s poor"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the story be -s right"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the story be -s young"
./mcfg_nt grammars/wmcfg/larsonian1.wmcfg -trees "the house be -s poor"
